# FreeSynth.org Configuration

# Site settings
title: FreeSynth
email: hi@freesynth.org
description: >- # This will appear in search engine results and the feed.xml site description
  FreeSynth.org - Your gateway to AI-powered creativity. Join us as we explore
  and empower artists, developers, and innovators with AI tools, tutorials,
  and inspiration.
baseurl: "" # Optional subpath of your site (e.g., /blog)
url: "https://freesynth.org" # Base URL for the site
twitter_username: adnjoo
github_username:  andrewnjoo

# Build settings
theme: minima
plugins:
  - jekyll-feed # RSS feed plugin for content syndication

# Exclude from processing
# Directories or files listed here will be skipped by Jekyll.
# Uncomment and adjust as necessary for FreeSynth.org.

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
